# Generated by Django 4.1.7 on 2023-03-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='video',
            field=models.FileField(blank=True, db_column='video', null=True, upload_to='videos/'),
        ),
    ]
