# Generated by Django 4.1.7 on 2023-03-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_newsmodel_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='video',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='video1',
            field=models.FileField(blank=True, db_column='video1', null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='video2',
            field=models.FileField(blank=True, db_column='video2', null=True, upload_to='videos/'),
        ),
    ]
